config/routes.rb
Rails.application.routes.draw do
  devise_for :teams
  root to: 'games#index'
  resources :members
  resources :games do
    resources :batting_orders
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batters_box_result.rb
class BattersBoxResult < ApplicationRecord
end

app/models/batting_order.rb
class BattingOrder < ApplicationRecord
  belongs_to :game
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :position
end

app/models/enemy_batting_order.rb
class EnemyBattingOrder < ApplicationRecord
end

app/models/enemy_member.rb
class EnemyMember < ApplicationRecord
end

app/models/enemy_position.rb
class EnemyPosition < ApplicationRecord
end

app/models/enemy_report.rb
class EnemyReport < ApplicationRecord
end

app/models/enemy_team.rb
class EnemyTeam < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team
  has_many :batting_orders, dependent: :destroy
  accepts_nested_attributes_for :batting_orders, allow_destroy: true
  
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :batting_orders
end

app/models/member_collection.rb
class MemberCollection
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  extend ActiveModel::Translation
  include ActiveModel::AttributeMethods
  include ActiveModel::Validations
  MEMBER_NUM = 3  # 同時にメンバーを作成する数
  attr_accessor :collection  # ここに作成したメンバーモデルが格納される

  # 初期化メソッド
  def initialize(attributes = [])
    if attributes.present?
      self.collection = attributes.map do |value|
        Member.new(
          team_id: value['team_id'],
          uniform_number: value['uniform_number'],
          grade: value['grade'],
          first_name: value['first_name'],
          last_name: value['last_name']
        )
      end
    else
    self.collection = MEMBER_NUM.times.map{ Member.new }
    end
  end

# レコードが存在するか確認するメソッド
  def persisted?
    false
  end

  # コレクションをDBに保存するメソッド
  def save
    is_success = true
    ActiveRecord::Base.transaction do
      collection.each do |result|
        # バリデーションを全てかけたいからsave!ではなくsaveを使用
        is_success = false unless result.save
      end
      # バリデーションエラーがあった時は例外を発生させてロールバックさせる
      raise ActiveRecord::RecordInvalid unless is_success
    end
    rescue
      p 'エラー'
    ensure
      return is_success
  end

end

app/models/order_collection.rb
class OrderCollection
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  extend ActiveModel::Translation
  include ActiveModel::AttributeMethods
  include ActiveModel::Validations
  USER_NUM = 9  # 同時にユーザーを作成する数
  attr_accessor :collection

  # 初期化メソッド
  def initialize(attributes = [])
    if attributes.present?
      self.collection = attributes.map do |value|
        Member.new(
          uniform_number: value['uniform_number'],
          grade: value['grade'],
          first_name: value['first_name'],
          last_name: value['last_name'],
          team_id: value['team_id']
        )
      end
    else
      self.collection = USER_NUM.times.map{ Member.new }
    end
  end

  # レコードが存在するか確認するメソッド
  def persisted?
    false
  end

  # コレクションをDBに保存するメソッド
  def save
    
    is_success = true
    ActiveRecord::Base.transaction do
      collection.each do |result|
        # バリデーションを全てかけたいからsave!ではなくsaveを使用
        is_success = false unless result.save!
      end
      # バリデーションエラーがあった時は例外を発生させてロールバックさせる
      raise ActiveRecord::RecordInvalid unless is_success
    end
    rescue
      p 'エラー'
    ensure
      return is_success
  end
end

app/models/position.rb
class Position < ActiveHash::Base
  self.data = [
   { id: 1, name: '--' },
   { id: 2, name: '投' },
   { id: 3, name: '捕' },
   { id: 4, name: '一' },
   { id: 5, name: '二' },
   { id: 6, name: '三' },
   { id: 7, name: '遊' },
   { id: 8, name: '左' },
   { id: 9, name: '中' },
   { id: 10, name: '右' }
  ]

  include ActiveHash::Associations
  has_many :batting_orders
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :games
  def email_required?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_team!, only: :new
  MEMBER_COUNT = 9
  
  def index
  end

  def new
    count = Member.where(team_id: current_team).count
    if count >= MEMBER_COUNT
      @game = Game.new
      MEMBER_COUNT.times { @game.batting_orders.build }
    else
      return redirect_to new_member_path
    end
  end

  def create
    @game = Game.new(games_params)

    if @game.valid?
      @game.save
      redirect_to root_path
    else
      render new
    end
  end

  private

  def games_params
    params.require(:game).permit(:game_name, :game_day,
      batting_orders_attributes: [:member_id, :batting_number, :position_id]).merge(team_id: current_team.id)
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all
	end

  def new
    if team_signed_in?
      @members = OrderCollection.new
    else
      return redirect_to new_team_session_path
    end
  end

  def create
    @members = OrderCollection.new(orders_params)
    if @members.valid?
      @members.save
      return redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      return redirect_to members_path
    else
      render :edit
    end
  end

  def destroy
    @member = Member.find(params[:id])
    if @member.destroy
      return redirect_to members_path
    else
      render :index
    end
  end



  private

  def member_params
    params.require(:member).permit(:uniform_number, :grade, :first_name,:last_name).merge(team_id: current_team.id)
  end

  def orders_params
    params.require(:members)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/index.html.erb
<div class="games-main-index">
  <header class='top-page-header'>
    <div class="header-title">
      <h1 class='title'>BaseBall Score</h1>
    </div>
    <ul class='lists-right'>
      <% if team_signed_in? %>
        <%# チーム名を記載 %>
        <li class='login'><%= link_to current_team.name %></li>
        <li><%= link_to 'ログアウト', destroy_team_session_path, method: :delete, class: "sign-up" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_team_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_team_registration_path, class: 'sign-up' %></li>
      <% end %>
    </ul>
  </header>
  <div class= "main" >
    <ul class='lists-center'>
      <li><%= link_to '試合登録', new_game_path, class: "game-regster" %></li>
      <li><%= link_to '選手登録', new_member_path, class: 'player-regster' %></li>
    </ul>
  </div>
  <div class="bb-footer">
    <div class="copyright-name">
      COPYRIGHT &#169;bbscore  ALL RIGHTS RESERVED.
    </div>
  </div>
</div>

app/views/games/new.html.erb
<div class="games-main">
	<div class="games">
		<div class="game-registration">試合登録画面</div>
	</div>
	<%= form_with(model: @game, url: games_path, local: true) do |form| %>
		<div class="game-inputs">
			<%= form.text_field :game_name, placeholder:"大会名", class:"tournament" %>
			<%= form.date_field :game_day, class:"game-date", placeholder:"日付", min: Date.current %>
		</div>
		<div class="orders">
			<table class="orders-new">
				<tr class="orders-new-registration">
					<th class="game-batting-order">打順</th>
					<th class="game-uniform-number">背番号</th>
					<th class="game-grade">学年</th>
					<th class="game-full-name">名前</th>
					<th class="game-defensive">守備</th>
				</tr>
				<%= form.fields_for :batting_orders do |field| %>
					<tr class="orders-new-registration">
						<td class="input-form-1">
							<%= field.text_field :batting_number, class:"input-game-uniform-number" %>
						</td>
						<td class="input-form-2">
							<%= field.hidden_field :member_id, value:7 %>
							<input type="text" class="input-game-uniform-number"/>
						</td>
						<td class="input-form-3">
							<input type="text" class="input-game-grade"/>
						</td>
						<td class="input-form-4">
							<input type="text" class="input-game-full-name"/>
						</td>
						<td class="input-form-5">
							<%= field.collection_select(:position_id, Position.all, :id, :name, {}, {class:"input-game-defensive"}) %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
		<div class="btn">
			<%= form.submit "登録", class:"btn-games-index" %>
		</div>
	<% end %>
</div>

app/views/games/show.html.erb
<% array = [A,B,C,D,E,F,G,H,I]%>

<table>
  <thead>
    <tr>
      <th>打席/回数</th>
      <td></td>
      <% 9.times do |i| %>
        <td><%= i %></td>
      <% end %>
    </tr>
  </thead>
  <body>
    <% 9.times do |r| %>
      <tr>
        <th><%= r %><th>
        <td><%= array[r-1]%></td>
        <% 9.times do |c| %>
          <td class="height<%= r %> width<%= c %>"><%= c %></td>
        <% end %>
      </tr>
    <% end %>
  </body>
</table>

app/views/members/edit.html.erb
<div class="teams">
	<h1>チーム名選手編集</h1>
</div>
<%= form_with(model: @member, local: true) do |form| %>
	<div class="members">
		<table class="members-new">
			<tr class="members-new-tr-1">
				<th class="uniform-number">背番号</th>
				<th class="grade">学年</th>
				<th class="first-name">姓</th>
				<th class="last-name">名</th>
			</tr>
			<tr class="members-new-tr-2">
				<td class="uniform-number">
					<%= form.text_field :uniform_number, class:"input-uniform-number" %>
				</td>
				<td class="grade">
					<%= form.text_field :grade, class:"input-grade" %>
				</td>
				<td class="first-name">
					<%= form.text_field :first_name, class:"input-first-name" %>
				</td>
				<td class="last-name">
					<%= form.text_field :last_name, class:"input-last-name" %>
				</td>
			</tr>
		</table>
	</div>
	<div class="btn">
	<%= form.submit "登録", class:"members-btn" %>
		<%= link_to '一覧', members_path, class: 'btn-members-index' %>
	</div>
<% end %>
<%= link_to 'TOPに戻る', root_path, class: 'btn-members-index' %>

app/views/members/index.html.erb
<div class="member-index-main">
  <h2 class="member-index-title">選手メンバー 一覧</h2>

  <table class="index-box">
    <thead>
      <tr class="member-index-label">
        <td class="member-number">背番号</td>
        <td class="member-index-grade">学年</td>
        <td class="member-index-last-name">姓名</td>
       <td class="member-index-first-name">名前</td>
       <td class="member-index-edit"></td>
        <td class="member-index-delete"></td>
      </tr>
    </thead>
   <% @members.each do |member| %>
   <tbody>
    <%# ここでチームメンバーの一覧を表示させるメソッドを使用（20名毎にページネーション） %>
      <tr class="member-index">
        <td class="member-number">
          <%= member.uniform_number %>
        </td>
        <td class="member-index-grade">
          <%= member.grade %>
        </td>
       <td class="member-index-last-name">
         <%= member.first_name %>
       </td>
       <td class="member-index-first-name">
         <%= member.last_name %>
       </td>
        <td class="btn-member-index-edit">
          <%= link_to '編集', edit_member_path(member.id)  %>
        </td>
       <td class="btn-member-index-delete">
         <%= link_to '削除', member_path(member.id), method: :delete %>
        </td>
      </tr>
     <%# ここでチームメンバーの一覧を表示させるメソッドを使用（20名毎にページネーション） %>
     <%# データ数２０でページネーション %>
    </tbody>
    <% end %>
  </table>
  <%= link_to 'TOPに戻る', root_path, class: 'btn-members-index' %>
</div>

app/views/members/new.html.erb
<div class="members-main">
	<div class="teams">
		<h1>選手登録画面</h1>
	</div>
	<%= form_with(model: @members, url: members_path, local: true) do |form| %>
		<div class="members">
			<table class="members-new">
				<tr class="members-new-tr-1">
					<th class="uniform-number">背番号</th>
					<th class="grade">学年</th>
					<th class="first-name">姓</th>
					<th class="last-name">名</th>
				</tr>
				<% @members.collection.each do |member| %>
					<%= fields_for 'members[]', member do |field| %>
						<tr class="members-new-tr-2">
							<%= field.hidden_field :team_id, value:current_team.id %>
							<td class="uniform-number">
								<%= field.text_field :uniform_number, class:"input-uniform-number" %>
							</td>
							<td class="grade">
								<%= field.text_field :grade, class:"input-grade" %>
							</td>
							<td class="first-name">
								<%= field.text_field :first_name, class:"input-first-name" %>
							</td>
							<td class="last-name">
								<%= field.text_field :last_name, class:"input-last-name" %>
							</td>
						</tr>
					<% end %>
				<% end %>
			</table>
		</div>
		<div class="btn">
			<%= form.submit "登録", class:"members-btn" %>
			<%= link_to '一覧', members_path, class: 'btn-members-index' %>
		</div>
	<% end %>
	<%= link_to 'TOPに戻る', root_path, class: 'btn-members-index' %>
</div>